Services/inube.Services.Notification/Controllers/TemplateController.cs
using inube.Services.Notification.Controllers;
using inube.Services.Notification.Controllers.DMS.DMSService;
using inube.Services.Notification.Helpers;
using inube.Services.Notification.Models;
using iNube.Utility.Framework.Model;
using iNube.Utility.Framework.Notification;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;
using TemplateDemo.Models;

namespace inube.Services.Notification.Template
{
    public class TemplateController : Controller
    {
        private readonly IHostingEnvironment _host;
        private readonly IEmailService _emailService;
        private readonly IConfiguration _configuration;
        private ICompositeViewEngine _viewEngine;
       // private string number;
        private readonly IDMSService _iDMSService;
        private readonly INEmailService _emailNService;
        public TemplateController(IDMSService idMSService,IHostingEnvironment host, INEmailService emailNService, IEmailService emailService, IConfiguration configuration, ICompositeViewEngine viewEngine)
        {
            _viewEngine = viewEngine;
            _host = host;
            _emailService = emailService;
            _configuration = configuration;
            _iDMSService = idMSService;
            _emailNService = emailNService;
        }
        public IActionResult Index()
        {
            return View();
        }
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        public async Task<IActionResult> EmailPatner(PartnerEmail partnerEmail)
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            //PolicyModel model = GetPolicyModel();
            //var response = RenderPartialViewToString("PolicyTemplate", model);
            //// the base URL to resolve relative images and css
            ////String thisPageUrl = this.ControllerContext.HttpContext.Request.Url.AbsoluteUri;
            ////String baseUrl = thisPageUrl.Substring(0, thisPageUrl.Length -"Home/ConvertThisPageToPdf".Length);
            //byte[] bytes1 = Encoding.UTF8.GetBytes(response.Result);
            //byte[] bytes = ToByteArray(response.Result);

            //TemplateHelper templateHelper = new TemplateHelper(_emailService, _configuration);
            //await templateHelper.ProcessNotificationAsync(bytes1, model);
            return View(partnerEmail);
        }
        public static byte[] ToByteArray(string value)
        {
            char[] charArr = value.ToCharArray();
            byte[] bytes = new byte[charArr.Length];
            for (int i = 0; i < charArr.Length; i++)
            {
                byte current = Convert.ToByte(charArr[i]);
                bytes[i] = current;
            }

            return bytes;
        }
        private byte[] EncodeToBytes(string str)
        {
            byte[] bytes = new byte[str.Length * sizeof(char)];
            System.Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);
            return bytes;
        }
        public async System.Threading.Tasks.Task<IActionResult> PartnerPDFDownload()
        {
            PartnerEmail model = new PartnerEmail() { PartnerName = "XYZ", PartnerId = "12345", MobileNo = "987675634", Designation = "SE", Website = "www.abc.com" };
            var root = _host.ContentRootPath;
            var wwwroot = _host.WebRootPath;

            var pdfname = String.Format("{0}.pdf", Guid.NewGuid().ToString());
            var path = Path.Combine(wwwroot, "PdfFiles", pdfname);
            path = Path.GetFullPath(path);
            var content = new ViewAsPdf("~/views/Template/EmailPatner.cshtml", model)
            {
                FileName = "Partner" + model.PartnerId + ".pdf",
                PageSize = Size.A4,
                PageOrientation = Orientation.Landscape,
                PageMargins = { Left = 1, Right = 1 },
                //CustomSwitches = string.Format("--footer-html {0} --footer-spacing -10 ", " http://localhost:portnumber/Template/ActionName?number=" + number),
                //SaveOnServerPath = path,
                //PageWidth = 297
                //CustomSwitches="--page-offset 0 --footer-center [page] --footer-font-size 8"

            };
            var binary = await content.BuildFile(ControllerContext);
            TemplateHelper templateHelper = new TemplateHelper(_emailService,_emailNService, _configuration);
            //await templateHelper.ProcessNotificationAsync(binary);
            // File.WriteAllBytes(@"C:\testpdf.pdf", binary);
            return content;
        }


        public IActionResult PartnerPDFView()
        {
            PartnerEmail model = new PartnerEmail() { PartnerName = "XYZ", PartnerId = "123", MobileNo = "987675634", Designation = "SE", Website = "www.abc.com" };
            return new ViewAsPdf("~/views/Template/EmailPatner.cshtml", model);
        }

        public IActionResult CreateUser(PartnerEmail model)
        {
            return View(model);
        }
        public IActionResult Partner(PartnerEmail model)
        {
            return View(model);
        }
        public IActionResult PolicyIssue(PartnerEmail model)
        {
            return View(model);
        }
        public IActionResult TestEmail()
        {
            PartnerEmail model = new PartnerEmail() { PolicyNo = "11000011", ProductCode = "P123", ProductName = "MICA", PartnerCode = "ABC123", PartnerName = "QWERTY" };
            return View(model);
        }

        public IActionResult ProductApi()
        {
            ProductApiModel model = GetProductApi();
                  return View(model);
        }
        //public IActionResult AptiQuestions()
        //{
        //    //AptiQuestionsModel model = GetAptiQuestions();
        //    QuestionsDetails model = GetQuestions();

        //    return View(model);
        //}
        //public IActionResult AptiQuestions()
        //{
        //    AptiQuestionsModel model = new AptiQuestionsModel();
        //    //AptiQuestionsModel model = GetAptiQuestions();
        //    return View(model);
        //}
        public IActionResult AptiQuestions()

        {

            //AptiQuestionsModel model = GetAptiQuestions();

            var model = GetQuestions(1, 1);



            return View(model);

            //var content = new ViewAsPdf("~/views/Template/AptiQuestions.cshtml", model)

            //{

            //    FileName = "QuestionSet" + model.AllQuestions[0].QBText + ".pdf",

            //    PageSize = Size.A4,

            //    PageOrientation = Orientation.Portrait,

            //    PageMargins = { Left = 1, Right = 1 },

            //    //SaveOnServerPath = path,

            //    //PageWidth = 297

            //};

            //return content;

        }

        public IActionResult PolicyTemplate()
        {
            PolicyModel model = GetPolicyModel();
            //var content = new ViewAsPdf("~/views/Template/PolicyTemplate.cshtml", model)
            //{
            //    FileName = "Partner" + model.policyDetails.PartnerName + ".pdf",
            //    PageOrientation = Orientation.Portrait,
            //    PageMargins = { Left = 1, Right = 1 },
            //    //SaveOnServerPath = path,
            //    //PageWidth = 297
            //};
            return View(model);
            //return content;
        }
        
        public IActionResult QuotationPdf(string proposerName)
        {
            QuotationModel model = GetQuotation();
           
            //var content = new ViewAsPdf("~/views/Template/QuotationPdf.cshtml", model)
            //{
            //    FileName = "Partner.pdf",
            //    PageSize = Size.A4,
            //    PageOrientation = Orientation.Portrait,
            //    PageMargins = { Left = 1, Right = 1 },
            
            //};

            //return View(model);
            return View(model);
        }
        public async System.Threading.Tasks.Task<IActionResult> PolicyIssueTemplate(PolicyModel model)
        {
            //policy model
            if (model.customer == null)
            {
                model = GetPolicyModel();
            }
            var content = new ViewAsPdf("~/views/Template/PolicyIssueTemplate.cshtml", model)
            {
                FileName = "Partner" + model.policyDetails.PartnerName + ".pdf",
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait,
                PageMargins = { Left = 1, Right = 1 },
                //SaveOnServerPath = path,
                //PageWidth = 297
            };
            if (ControllerContext.ActionDescriptor != null)
            {
                var binary = await content.BuildFile(ControllerContext);
                TemplateHelper templateHelper = new TemplateHelper(_emailService,_emailNService, _configuration);
                await templateHelper.ProcessNotificationAsync(model.PolicyNumber, binary, model.EmailTest);
            }
            else
            {
                //ControllerContext controllerContext = new ControllerContext(
                //new ActionContext(ControllerContext.HttpContext, new RouteData(), new ControllerActionDescriptor()) );
                var binary = await content.BuildFile(ControllerContext);
                TemplateHelper templateHelper = new TemplateHelper(_emailService,_emailNService, _configuration);

Services/inube.Services.Notification/Views/Shared/_EmailLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="index.css">
    <title>EmailPatner</title>
    <style type="text/css">
        body {
            background-color: #ffffff;
            color: #333;
            margin: 0;
            font-family: Roboto, Helvetica, Arial, sans-serif;
            font-weight: 300;
            line-height: 1.5em;
        }

        .main {
            width: 1024px;
            height: auto;
        }

        .header {
            background-color: #f5f5f5;
            height: 20%;
            margin-left: 24%;
            width: 50%;
            margin-top: 2%
        }

        .footer {
            background-color: #f5f5f5;
            height: 20%;
            margin-left: 24%;
            width: 50%;
            margin-bottom: 2%
        }

        .fotter-content {
            font-weight: 500;
            text-align: center;
            padding-top: 2%;
            font-size: 14px;
        }

        .svg {
            height: 10%;
            width: 20%;
            margin-left: 2%;
        }

        .container {
            margin-left: 24%;
            max-width: 50%;
        }

            h1 {
                bottom: 39px;
                left: 6%;
       
                position: relative;
                font-size: 14px;
            }

        .heading {
            font-size: 14px;
            font-weight: 500;
        }

        .prara {
            font-size: 16px;
            font-weight: 400;
            margin: 15px 0px 0px 0px;
        
        }

        .right {
            float: right;
            position: relative;
            bottom: 12px;
        }


        ul {
            list-style: none
        }

        li {
            background: transparent;
            display: inline-block;
            /* inline block hack for IE 6&7 */
            zoom: 1;
            *display: inline;
            padding: 4px;
            color: white
        }



        .light {
            color: rgb(211, 211, 211);
        }


        a {
            font-weight: 500;
            text-align: center;
            padding-top: 2%;
            font-size: 14px;
            color: #333;
        }

            a:hover {
                color: rgb(80, 77, 241);
            }



        /*//////////////////////////////////////////////////////////////////////////*/

        /*          Tabel  Stye            */

        /*!
// CSS only Responsive Tables
// http://dbushell.com/2016/03/04/css-only-responsive-tables/
// by David Bushell
*/

        .rtable {
            /*!
  // IE needs inline-block to position scrolling shadows otherwise use:
  // display: block;
  // max-width: min-content;
  */
            display: inline-block;
            vertical-align: top;
            max-width: 100%;
            overflow-x: auto;
            /* optional - looks better for small cell values*/
            white-space: nowrap;
            border-collapse: collapse;
            border-spacing: 0;
        }

        .rtable,
        .rtable--flip tbody {
            /* optional - enable iOS momentum scrolling*/
            -webkit-overflow-scrolling: touch;
            /* scrolling shadows*/
            background: radial-gradient(left, ellipse, rgba(0,0,0, .2) 0%, rgba(0,0,0, 0) 75%) 0 center, radial-gradient(right, ellipse, rgba(0,0,0, .2) 0%, rgba(0,0,0, 0) 75%) 100% center;
            background-size: 10px 100%, 10px 100%;
            background-attachment: scroll, scroll;
            background-repeat: no-repeat;
        }

            .rtable th {
                font-size: 11px;
                text-align: left;
                text-transform: uppercase;
                background: #053f6c;
                color: white;
                font-weight: 500;
                text-transform: inherit;
            }

            .rtable th,
            .rtable td {
                padding: 6px 12px;
                border: 0.1px solid white;
            }

        .rtable--flip {
            display: flex;
            overflow: hidden;
            background: none;
        }

            .rtable--flip thead {
                display: flex;
                flex-shrink: 0;
                min-width: min-content;
            }

            .rtable--flip tbody {
                display: flex;
                position: relative;
                overflow-x: auto;
                overflow-y: hidden;
            }

            .rtable--flip tr {
                display: flex;
                flex-direction: column;
                min-width: min-content;
                flex-shrink: 0;
            }

            .rtable--flip td,
            .rtable--flip th {
                display: block;
            }

            .rtable--flip td {
                background-image: none !important;
                /* border-collapse is no longer active*/
                border-left: 0;
            }

                /* border-collapse is no longer active*/
                .rtable--flip th:not(:last-child),
                .rtable--flip td:not(:last-child) {
                    border-bottom: 0;
                }

        table {
            margin-bottom: 30px;
        }

        .transparent {
            background-color: white !important;
        }



        /*          Matrix                                   */

        .matrixtb {
            /*!
  // IE needs inline-block to position scrolling shadows otherwise use:
  // display: block;
  // max-width: min-content;
  */
            display: inline-block;
            vertical-align: top;
            max-width: 100%;
            overflow-x: auto;
            /* optional - looks better for small cell values*/
            white-space: nowrap;
            border-collapse: collapse;
            border-spacing: 0;
        }

        .matrixtb,
        .matrixtb--flip tbody {
            /* optional - enable iOS momentum scrolling*/
            -webkit-overflow-scrolling: touch;
            /* scrolling shadows*/
            background: radial-gradient(left, ellipse, rgba(0,0,0, .2) 0%, rgba(0,0,0, 0) 75%) 0 center, radial-gradient(right, ellipse, rgba(0,0,0, .2) 0%, rgba(0,0,0, 0) 75%) 100% center;
            background-size: 10px 100%, 10px 100%;
            background-attachment: scroll, scroll;
            background-repeat: no-repeat;
        }


            .matrixtb th {
                font-size: 18px;
                text-align: left;
                text-transform: uppercase;
                background: #ffffff;
                color: #2878b6;
                font-weight: 500;
                padding: 5%;
                width: 200px;
                text-transform: capitalize
            }

            .matrixtb td {
                color: #333;
                font-size: 14px;
                font-weight: 500;
            }

            .matrixtb th,
            .matrixtb td {
                padding: 6px 12px;
                border: 0.1px solid rgb(207, 207, 207);
                border-top-style: none;
                border-right-style: none;
                border-left-style: none;
            }

        .matrixtb--flip {
            display: flex;
            overflow: hidden;
            background: none;
        }

            .matrixtb--flip thead {
                display: flex;
                flex-shrink: 0;
                min-width: min-content;
            }

            .matrixtb--flip tbody {
                display: flex;
                position: relative;
                overflow-x: auto;
                overflow-y: hidden;
            }

            .matrixtb--flip tr {
                display: flex;
                flex-direction: column;
                min-width: min-content;
                flex-shrink: 0;
            }

            .matrixtb--flip td,
            .matrixtb--flip th {
                display: block;
            }

            .matrixtb--flip td {
                background-image: none !important;
                /* border-collapse is no longer active*/
                border-left: 0;
            }

                /* border-collapse is no longer active*/
                .matrixtb--flip th:not(:last-child),
                .matrixtb--flip td:not(:last-child) {
                    border-bottom: 0;
                }



    </style>
</head>
<body>

    <div class="header">
        @*<img src="https://brandmark.io/logo-rank/random/mcdonalds.png"  class="svg"/>*@
        @*<embed class="svg" src="~/images/logo.svg" alt="Logo" />
        <img src="~/images/logo.png" alt="logo" />*@
    </div>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <p class="heading">
            Regards,<br>
            Team MICA
        </p>
    </div>
    <div class="footer">

       
    </div>

</body>
</html>

Services/inube.Services.Notification/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - inube.Services.Notification</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Notification</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="EmailPatner">EmailTemplate</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PartnerPDFView">View Partner</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PartnerPDFDownload">Partner PDF Download</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="CreateUser">UserTemplate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="Partner">PartnerTemplate</a>
        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PolicyIssue">PolicyIssueTemplate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PartnerPDFDownload">PDF Download</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PolicyTemplate">Policy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="PolicyIssueTemplate">PDFCertificate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="InsCertificateMultiCover">MultiCover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="ProductApi">ProdKit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="TaxInvoice">Invoice</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="QuotationPdf">QuotationTemplate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="ProductApiKit">ApiKit</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - inube.Services.Notification - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>